#!/usr/bin/env python
import subprocess

units = {
  1: 'dong_thap',
  2: 'an_giang',
  3: 'bac_lieu',
  4: 'ben_tre',
  5: 'can_tho',
  6: 'ca_mau',
  7: 'hau_giang',
  8: 'kien_giang',
  9: 'long_an',
  10: 'soc_trang',
  11: 'tien_giang',
  12: 'tra_vinh',
  13: 'vinh_long',
  14: 'bac_ninh',
  15: 'hai_duong',
  16: 'haiphong',
  17: 'hung_yen',
  18: 'hanoi',
  19: 'ha_nam',
  20: 'ha_tay',
  21: 'nam_dinh',
  22: 'ninh_binh',
  23: 'thai_binh',
  24: 'vinh_phuc',
  25: 'bac_giang',
  26: 'bac_can',
  27: 'cao_bang',
  28: 'ha_giang',
  29: 'lang_son',
  30: 'lao_cai',
  31: 'phu_tho',
  32: 'quang_ninh',
  33: 'thai_nguyen',
  34: 'tuyen_quang',
  35: 'yen_bai',
  36: 'dong_nai',
  37: 'ba_ria_vung_tau',
  38: 'binh_duong',
  39: 'binh_phuoc',
  40: 'binh_thuan',
  41: 'ho_chi_minh_city',
  42: 'ninh_thuan',
  43: 'tay_ninh',
  44: 'ha_tinh',
  45: 'nghe_an',
  46: 'quang_binh',
  47: 'quang_tri',
  48: 'thua_thien_hue',
  49: 'thanh_hoa',
  50: 'da_nang',
  51: 'binh_dinh',
  52: 'khanh_hoa',
  53: 'phu_yen',
  54: 'quang_nam',
  55: 'quang_ngai',
  56: 'dien_bien',
  57: 'hoa_binh',
  58: 'lai_chau',
  59: 'son_la',
  60: 'dak_lak',
  61: 'dac_nong',
  62: 'gia_lai',
  63: 'kon_tum',
  64: 'lam_dong'
}

for i, v in units.iteritems():
  cmd = "ogr2ogr -f GeoJSON -where \"ID_2 = {0}\" units/{1}.geojson adm3.shp".format(i, v)
  subprocess.call(cmd, shell=True)
  cmd = "topojson -o units/{0}.json --id-property ID_3 -p name_vi=NAME_3 -p name_en=VARNAME_3 -p type_vi=TYPE_3 -p type_en=ENGTYPE_3 -- units/{0}.geojson".format(v)
  subprocess.call(cmd, shell=True)
  print "----------------------------------"